apiVersion: v2
name: k8gb
description: A Helm chart for Kubernetes Global Balancer
icon: https://www.k8gb.io/assets/images/icon-192x192.png
type: application
version: v0.8.3
appVersion: v0.8.3

dependencies:
  - name: coredns
    repository: https://absaoss.github.io/coredns-helm
    version: 1.15.3

home: https://www.k8gb.io/
sources:
  - https://github.com/k8gb-io/k8gb

keywords:
  - gslb
  - dns-lb
  - kuberneters-global-balancer
  - kubernetes-operator
  - balancer

maintainers:
  - email: dinar.valeev@absa.africa
    name: Dinar Valeev
  - email: jiri.kremser@gmail.com
    name: Jiri Kremser
  - email: kuritka@gmail.com
    name: Michal Kuritka
  - email: timofey.ilinykh@absa.africa
    name: Timofey Ilinykh
  - email: yury.tsarev@absa.africa
    name: Yury Tsarev

annotations:
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Seamless Upgrades
  artifacthub.io/crds: |
    - kind: Gslb
      version: v1beta1
      name: gslbs.k8gb.absa.oss
      displayName: Gslb
      description: Gslb resource for global load balancing strategy configuration
  artifacthub.io/crdsExamples: |
    - apiVersion: k8gb.absa.oss/v1beta1
      kind: Gslb
      metada:
        name: test-gslb-failover
        namespace: test-gslb
      spec:
        ingress:
          rules:
            - host: failover.test.k8gb.io # Desired GSLB enabled FQDN
              http:
                paths:
                - backend:
                    serviceName: frontend-podinfo # Service name to enable GSLB for
                    servicePort: http
                  path: /
        strategy:
          type: failover # Global load balancing strategy
          primaryGeoTag: eu-west-1 # Primary cluster geo tag
