[build]
  command = "pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-simple-hooks && mkdocs build"
  publish = "site/"

[build.environment]
  PYTHON_VERSION = "3.8"
