{{- if or .Values.ns1.enabled .Values.rfc2136.enabled .Values.azuredns.enabled .Values.cloudflare.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: k8gb-external-dns
      securityContext:
{{ toYaml .Values.externaldns.securityContext  | indent 8 }}
      containers:
      - name: external-dns
        image: {{ .Values.externaldns.image }}
        args:
        - --source=crd
{{- $dnsZonesRaw := include "k8gb.dnsZonesString" . }}
{{- $dnsZones := split ";" $dnsZonesRaw }}
{{- range $dnsZones }}
        {{- $parts := split ":" . }}
        {{- $parentZone := index $parts "_0" }}
        - --domain-filter={{ $parentZone }} # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
{{- end }}
        - --policy=sync # enable full synchronization including record removal
        - --log-level=debug # debug only
        - --managed-record-types=A
        - --managed-record-types=CNAME
        - --managed-record-types=NS
        - --interval={{ .Values.externaldns.interval }}
        - --label-filter=k8gb.absa.oss/dnstype=extdns # filter out only relevant DNSEntrypoints
        - --txt-owner-id={{ include "k8gb.extdnsOwnerID" . }}
        - --txt-prefix=k8gb-{{ .Values.k8gb.clusterGeoTag }}- # add custom prefix to TXT records, critical for Cloudflare NS record creation
        - --provider={{ include "k8gb.extdnsProvider" . }}
        {{ include "k8gb.extdnsProviderOpts" . }}
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          readOnlyRootFilesystem: true
        {{- with .Values.externaldns.extraEnv }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.rfc2136.rfc2136auth.gssTsig.enabled }}
        volumeMounts:
          - mountPath: /etc/krb5.conf
            name: kerberos-config-volume
            subPath: krb5.conf
          {{- with .Values.externaldns.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      dnsPolicy: {{ .Values.externaldns.dnsPolicy }}
      volumes:
        - name: kerberos-config-volume
          configMap:
            name: {{ .Values.rfc2136.rfc2136auth.gssTsig.kerberosConfigmap }}
            defaultMode: 420
        {{- with .Values.externaldns.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.azuredns.enabled }}
        volumeMounts:
          - name: azure-config-file
            mountPath: /etc/kubernetes/
            readOnly: true
      volumes:
        - name: azure-config-file
          secret:
            secretName: {{ .Values.azuredns.authSecretName | default "external-dns-secret-azure" }}
      {{- end }}
{{- end }}
