{{- if or .Values.ns1.enabled .Values.route53.enabled .Values.rfc2136.enabled .Values.cloudflare.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: k8gb-external-dns
      securityContext:
{{ toYaml .Values.externaldns.securityContext  | indent 8 }}
      containers:
      - name: external-dns
        image: {{ .Values.externaldns.image }}
        args:
        - --source=crd
        - --domain-filter={{ .Values.k8gb.edgeDNSZone }} # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --policy=sync # enable full synchronization including record removal
        - --log-level=debug # debug only
        - --managed-record-types=A
        - --managed-record-types=CNAME
        - --managed-record-types=NS
        - --annotation-filter=k8gb.absa.oss/dnstype=extdns # filter out only relevant DNSEntrypoints
        - --txt-owner-id={{ include "k8gb.extdnsOwnerID" . }}
        - --txt-prefix=k8gb-{{ .Values.k8gb.clusterGeoTag }}- # add custom prefix to TXT records, critical for Cloudflare NS record creation
        - --provider={{ include "k8gb.extdnsProvider" . }}
        {{- if and .Values.route53.assumeRoleArn (not .Values.route53.secret) }}
        - --aws-assume-role={{ .Values.route53.assumeRoleArn }}
        {{- end }}
        {{ include "k8gb.extdnsProviderOpts" . }}
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          readOnlyRootFilesystem: true
      {{- if .Values.route53.secret }}
        env:
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /.aws/credentials
        volumeMounts:
          - name: aws-credentials
            mountPath: /.aws
            readOnly: true
      volumes:
        - name: aws-credentials
          secret:
            secretName: {{ .Values.route53.secret }}
      {{- end }}
      {{- if .Values.rfc2136.rfc2136auth.gssTsig.enabled }}
        volumeMounts:
          - mountPath: /etc/krb5.conf
            name: kerberos-config-volume
            subPath: krb5.conf
      volumes:
        - name: kerberos-config-volume
          configMap:
            name: {{ .Values.rfc2136.rfc2136auth.gssTsig.kerberosConfigmap }}
            defaultMode: 420
      {{- end }}
        
{{- end }}
