kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 81
    protocol: TCP
  - containerPort: 443
    hostPort: 444
    protocol: TCP
  - containerPort: 53
    hostPort: 5054
    protocol: UDP
