---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unhealthy-httproute
  namespace: test-gslb-gatewayapi
spec:
  parentRefs:
  - name: gatewayapi
    namespace: istio-ingress
  hostnames:
    - unhealthy-httproute.cloud.example.com
  rules:
  - backendRefs:
    - name: unhealthy-app
      port: 80
---
apiVersion: k8gb.io/v1beta1
kind: Gslb
metadata:
  name: unhealthy-httproute
  namespace: test-gslb-gatewayapi
spec:
  resourceRef:
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    name: unhealthy-httproute
  strategy:
    type: roundRobin
    dnsTtlSeconds: 30
