apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: failover-ingress
  namespace: test-gslb
spec:
  ingressClassName: nginx
  rules:
  - host: failover.cloud.example.com
    http:
      paths:
      - backend:
          service:
            name: frontend-podinfo
            port:
              name: http
        path: /
        pathType: Prefix
---
apiVersion: k8gb.io/v1beta1
kind: Gslb
metadata:
  name: failover-ingress
  namespace: test-gslb
spec:
  resourceRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: failover-ingress
  strategy:
    type: failover
    primaryGeoTag: eu
