---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: notfound-httproute
  namespace: test-gslb-gatewayapi
spec:
  parentRefs:
  - name: gatewayapi
    namespace: istio-ingress
  hostnames:
    - notfound-httproute.cloud.example.com
  rules:
  - backendRefs:
    - name: non-existing-app
      port: 9898
---
apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: notfound-httproute
  namespace: test-gslb-gatewayapi
spec:
  resourceRef:
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    name: notfound-httproute
  strategy:
    type: roundRobin
    dnsTtlSeconds: 30
