apiVersion: kgb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: test-gslb-failover
  namespace: test-gslb
spec:
  ingress:
    rules:
      - host: failover.cloud.example.com
        http:
          paths:
          - backend:
              serviceName: frontend-podinfo # Gslb should reflect Healthy status and create associated DNS records
              servicePort: http
            path: /
  strategy:
    type: failover
    primaryGeoTag: eu
