apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: roundrobin-ingress
  namespace: test-gslb
spec:
  ingress:
    ingressClassName: nginx
    rules:
      - host: notfound.cloud.example.com # This is the GSLB enabled host that clients would use
        http: # This section mirrors the same structure as that of an Ingress resource and will be used verbatim when creating the corresponding Ingress resource that will match the GSLB host
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: non-existing-app # Gslb should reflect NotFound status
                  port:
                    name: http
      - host: unhealthy.cloud.example.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                  name: unhealthy-app # Gslb should reflect Unhealthy status
                  port:
                    name: http
      - host: roundrobin.cloud.example.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                  name: frontend-podinfo # Gslb should reflect Healthy status and create associated DNS records
                  port:
                    name: http
  strategy:
    type: roundRobin # Use a round robin load balancing strategy, when deciding which downstream clusters to route clients too
    splitBrainThresholdSeconds: 300 # Threshold after which external cluster is filtered out from delegated zone when it doesn't look alive
    dnsTtlSeconds: 30 # TTL value for automatically created DNS records
