k8gb:
  reconcileRequeueSeconds: 10
  dnsZones:
    - dnsZoneNegTTL: 10
      loadBalancedZone: cloud.example.com
      parentZone: example.com
  log:
    format: simple
    level: debug

coredns:
  serviceType: NodePort
  servers:
  - zones:
    - zone: .
      use_tcp: true
    port: 5353
    servicePort: 53
    nodePort: 30053
    plugins:
    - name: prometheus
      parameters: 0.0.0.0:9153

extdns:
  enabled: true
  fullnameOverride: "k8gb-external-dns"
  provider:
    name: rfc2136
  domainFilters:
    - example.com
  dnsPolicy: ClusterFirst
  env:
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: rfc2136
        key: secret
  extraArgs:
    rfc2136-tsig-axfr:
    rfc2136-tsig-secret-alg: hmac-sha256
    rfc2136-tsig-keyname: externaldns-key
    rfc2136-host: host.k3d.internal
    rfc2136-port: 1053
    rfc2136-zone: example.com
