server:
  enabled: true
  persistentVolume:
    enabled: false # emptyDir, all data is lost when pod restarts
  service:
    servicePort: 9090
    type: LoadBalancer

alertmanager:
  enabled: false
#  service:
#    nodePort: 30091 # allowed port range between 30000 and 32768
#    servicePort: 9091
#    type: NodePort

prometheus-pushgateway:
  enabled: false
#  service:
#    nodePort: 30092 # allowed port range between 30000 and 32768
#    servicePort: 9092
#    type: NodePort
