apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohmyglb
  namespace: ohmyglb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ohmyglb
  template:
    metadata:
      labels:
        name: ohmyglb
    spec:
      serviceAccountName: ohmyglb
      containers:
        - name: ohmyglb
          image: {{ .Values.ohmyglb.image }}
          command:
          - ohmyglb
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ohmyglb"
            - name: CLUSTER_GEO_TAG
              value: {{ quote .Values.ohmyglb.clusterGeoTag }}
            - name: EXT_GSLB_CLUSTERS_GEO_TAGS
              value: {{ .Values.ohmyglb.extGslbClustersGeoTags }}
            - name: EDGE_DNS_ZONE
              value: {{ .Values.ohmyglb.edgeDNSZone }}
            - name: DNS_ZONE
              value: {{ .Values.ohmyglb.dnsZone }}
            {{ if .Values.infoblox.enabled }}
            - name: INFOBLOX_GRID_HOST
              valueFrom:
                configMapKeyRef:
                  name: infoblox
                  key: INFOBLOX_GRID_HOST
            - name: INFOBLOX_WAPI_VERSION
              valueFrom:
                configMapKeyRef:
                  name: infoblox
                  key: INFOBLOX_WAPI_VERSION
            - name: INFOBLOX_WAPI_PORT
              valueFrom:
                configMapKeyRef:
                  name: infoblox
                  key: INFOBLOX_WAPI_PORT
            - name: EXTERNAL_DNS_INFOBLOX_WAPI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: external-dns
                  key: EXTERNAL_DNS_INFOBLOX_WAPI_USERNAME
            - name: EXTERNAL_DNS_INFOBLOX_WAPI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: external-dns
                  key: EXTERNAL_DNS_INFOBLOX_WAPI_PASSWORD
            {{ end }}

