{{ if or .Values.route53.enabled .Values.ns1.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: k8gb-coredns-lb
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: udp-53
    port: 53
    protocol: UDP
  selector:
    app.kubernetes.io/instance: k8gb
    app.kubernetes.io/name: coredns
  type: LoadBalancer
{{ end }}
