kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8gb
subjects:
- kind: ServiceAccount
  name: k8gb
  namespace: k8gb
roleRef:
  kind: ClusterRole
  name: k8gb
  apiGroup: rbac.authorization.k8s.io
