apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    k8gb.io/strategy: failover
    k8gb.io/primary-geotag: eu
  labels:
    app: notfound-broken
  name: broken-test-gslb-annotation-failover
spec:
  ingressClassName: nginx
  rules:
  - host: notfound-broken.cloud.example.com
