apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    k8gb.io/strategy: failover
    k8gb.io/primary-geotag: "eu"
  labels:
    app: test-ingress-annotation-failover
  name: test-gslb
spec:
  ingressClassName: nginx
  rules:
    - host: test-ingress-annotation-failover.cloud.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-podinfo
                port:
                  name: http
