apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    k8gb.io/strategy: roundRobin
  name: test-gslb-annotation
spec:
  rules:
  - host: notfound.cloud.example.com
    http:
      paths:
      - backend:
          serviceName: non-existing-app
          servicePort: http
        path: /
  - host: unhealthy.cloud.example.com
    http:
      paths:
      - backend:
          serviceName: unhealthy-app
          servicePort: http
        path: /
  - host: roundrobin.cloud.example.com
    http:
      paths:
      - backend:
          serviceName: frontend-podinfo
          servicePort: http
        path: /
